include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.config.dart"
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    camel_case_types: true
    constant_identifier_names: true
    deprecated_consistency: true
    implementation_imports: true
    no_duplicate_case_values: true
    prefer_conditional_assignment: true
    prefer_const_constructors_in_immutables: true
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true
